# Generated by Django 4.0.5 on 2022-06-28 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processarbot',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.categoria'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
