# Generated by Django 4.0.5 on 2022-06-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_seguidores', models.IntegerField(default=0)),
                ('qtd_seguindo', models.IntegerField(default=0)),
                ('qtd_publicacoes', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(blank=True, max_length=128, null=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
