# Generated by Django 4.0.5 on 2022-06-18 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_seguidores', models.IntegerField(default=0)),
                ('qtd_seguindo', models.IntegerField(default=0)),
                ('qtd_publicacoes', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(blank=True, max_length=128, null=True)),
                ('login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.login')),
            ],
        ),
    ]
